import Head from "next/head"
import { useEffect, useState } from "react";
import Card from "../../components/Card/Card";
import styles from "../../styles/Home.module.css";

const Cats = function () {
  const [cats, setCats] = useState([]);

  const fetchCats = async () => {
    const response = await fetch("/api/cats");
    console.log(response);
    const json = await response.json();
    setCats(json);
  };

  useEffect(() => {
    fetchCats();
  }, []);

  console.log(cats);

  return (
    <>
      <Head>
        <title>Our Cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5">
        <div className={styles.wrapper}>
          {cats.map((cat) => (
            <Card key={cat.id} {...cat} />
          ))}
        </div>
      </div>
    </>
  );
};

export default Cats;
